version: '3.4'

services:
  mongo:
    container_name: roulettedb
    image: mongo
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
      - "27017:27017"
  rouletteapi:
    image: rouletteapi
    build:
      context: .
      dockerfile: Services/Roulette.Api/Dockerfile
    ports:
      - 8080
    depends_on:
      - mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:      
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ~/.vsdbg:/remote_debugger:rw
    links:
      - mongo
